
server:
  port: 1433

spring:
  main:
    banner-mode: off
    datasource:
        url: jdbc:jtds:sqlserver://192.168.18.200:1433
        username: buh
        password: buh

    jpa:
      hibernate:
        ddl-auto: create