spring:
  main:
    banner-mode: off

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver

server:
  port: 8081
