-- Database: postgres

CREATE TABLE passports(
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      serial VARCHAR(100) NOT NULL CHECK (serial <> ''),
                      number INT NOT NULL CHECK (number > 0),
                      date_of_issue DATE
);

INSERT INTO users (first_name, last_name, birth_date, email) values ('Joel', 'Edgerton', '1974-06-23', NULL);
INSERT INTO users (first_name, last_name, birth_date, email) values ('Tom', 'Hardy', '1979-09-15', 'joelEd@gmail.com');
INSERT INTO users (first_name, last_name, birth_date, email) values ('Nicholas', 'Nolte', '1941-02-08', NULL);



-- 1 Создайте таблицу, хранящую документ, удостоверяющий личность (паспорт), для пользователей.
-- Свяжите таблицу паспортов с таблицей пользователей. Не у всех пользователей в БД может быть
-- указан паспорт, но каждому паспорту соответствует один пользователь. У паспорта должны быть
-- поля id, буквенная или числовая серия и номер. Создайте паспорта для двух пользователей.
-- Выполните запрос на получение информации о пользователях вместе с данными паспортов.
-- 2 Создайте таблицу для хранения адресов доставки товаров пользователя. Свяжите таблицу адресов
-- с таблицей пользователей. У одного пользователя может быть несколько адресов для доставки, но
-- каждый адрес принадлежит только одному пользователю. Выполните запрос на получение информации
-- о пользователях вместе с адресами.

-- CREATE TABLE client_app_statistics(
--                                       id BIGINT NOT NULL,
--                                       client_app_name VARCHAR(100) NOT NULL CHECK (client_app_name <> ''),
--                                       client_app_count INT NOT NULL
-- );
--
-- INSERT INTO client_app_statistics (client_app_name, client_app_count) values ('Chrome browser', 10);
-- UPDATE client_app_statistics SET client_app_count = client_app_count + 1 WHERE client_app_name = 'Chrome browser';